server:
  port: 8082


spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:mysql://localhost:3306/woro
    username: root
    password: root
    driver:
      class-name: com.mysql.cj.jdbc.driver
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update